### ISSUE TITLE
mismatch in code between github and published python module

### ISSUE THREAD

**Issue by robofoundry** [lefuturiste/BMI160-i2c#11]
There seems to be a difference between the code that is available in github repo and the module that can be installed from https://pypi.org/project/BMI160-i2c/. Even though the version installed says 0.5 it seems to be missing several constants and the parameters to initialize sensor.

The workaround for me was to uninstall the module that was installed by pip and install it from code from this github repo like this:

pip uninstall bmi160-i2c
git clone https://github.com/lefuturiste/BMI160-i2c.git
cd BMI160-i2c
sudo python3 setup.py install

In addition, the all.py example will only work if the i2c addr is default addr. I have submitted a pull request to allow anyone to easily change it in all.py example as well.

Hope that helps someone.

**Comment by lefuturiste** [comment]
yep, I'm merging your PR and updating with pypi.org

**Comment by lefuturiste** [comment]
now at version 0.6

**Comment by robofoundry** [comment]
That is super nice of you to publish the new version 0.6 so fast, much appreciated!! I'll uninstall the one from code and try out the 0.6 now on both my robot RPi and host computer. Thanks so much.
