### ISSUE TITLE
sleep_us incorrect? 

### ISSUE THREAD

**Issue by xtile** [lefuturiste/BMI160-i2c#2]
def sleep_us(duration):
  return sleep(duration * 0.0001)

I guess there should be 0.000001, ie 10^-6

**Comment by lefuturiste** [comment]
yes it's 0.000001 my mistake :)

**Comment by lefuturiste** [comment]
Fixed in 66575b8b89c908611b6ddc2fae2cafc33fda2ea2 and with version `0.4`
