### ISSUE TITLE
STEP_* definitions are missing

### ISSUE THREAD

**Issue by meavydev** [lefuturiste/BMI160-i2c#4]
I think they should be something like:

STEP_BUF_MIN_BIT    = (0)
STEP_BUF_MIN_LEN    = (4)

## Step counter definitions
STEP_MODE_NORMAL    = (0)
STEP_MODE_SENSITIVE = (1)
STEP_MODE_ROBUST    = (2)
STEP_MODE_UNKNOWN   = (0)

**Comment by meavydev** [comment]
Also it uses serial_buffer_transfer() which doesn't exist and can probably be removed.

**Comment by meavydev** [comment]
Finally got Step count running...
Get Count is wrong:

  def getStepCount(self):
    buffer = [0]*2
    buffer[0] = self._reg_read(registers.STEP_CNT_L)
    buffer[1] = self._reg_read(registers.STEP_CNT_H)
    return ((buffer[1]) << 8) | buffer[0]

Missing Interrupt definitions:
## Interrupt definitions
INT1_OUTPUT_EN      = (3)
INT1_OD             = (2)
INT1_LVL            = (1)
LATCH_MODE_BIT      = (0)
LATCH_MODE_LEN      = (4)

More Step bits:
STEP_BUF_MIN_BIT    = (0)
STEP_CNT_EN_BIT     = (3)
STEP_EN_BIT         = (3)
STEP_BUF_MIN_LEN    = (4)

So this is the code you need:
    # Step detection requires interrupt config
    # See https://github.com/BoschSensortec/BMI160_driver#configuring-step-detector-interrupt
    sensor.setIntStepEnabled(True)
    # push-pull mode interrupt
    sensor.setInterruptDrive(0)
    # 0 = non-latched
    sensor.setInterruptLatch(0)
    # 0 = active-high
    sensor.setInterruptMode(0)
    sensor.setIntEnabled(True)
    # Normal step detection mode
    sensor.setStepDetectionMode(definitions.STEP_MODE_NORMAL)
    sensor.resetStepCount()
    sensor.setStepCountEnabled(True)

**Comment by lefuturiste** [comment]
Hey, thanks for contributing, could you create a Pull Request Instead ? So we can all agree on the changes to do.

**Comment by meavydev** [comment]
remote: Permission to lefuturiste/BMI160-i2c.git denied to meavydev.
So no I can't...

**Comment by lefuturiste** [comment]
Yes, totally normal behaviour

You need to make a fork and then submit your changes by opening a Pull Request.

I don't known if you known how to do it but in case you don't known:

Little tutorial: https://codeburst.io/a-step-by-step-guide-to-making-your-first-github-contribution-5302260a2940

But in short:
- Fork this repository (this will create a copy of this repository by under your user space so you will have the permission to edit)
- Clone the forked repository on your machine
- Make the changes that your need
- Add/Commit
- Push
- Open a Pull Request

**Comment by meavydev** [comment]
Ah. Forking... never used it as we develop on Github but not open projects, so we just use branches ;) 
PR created.

**Comment by lefuturiste** [comment]
PR #5 merged
