### ISSUE TITLE
Stuck at "Trying to initialize the sensor..."

### ISSUE THREAD

**Issue by sardanian** [lefuturiste/BMI160-i2c#6]
I have it wired up properly and my i2c address is showing as 0x6A which I changed, but it is not getting past
sensor = Driver(0x6A)

Any advice on what is going on? Anything to inspect or see? I am trying this on a Raspberry Pi 4.

Thank you

**Comment by lefuturiste** [comment]
This seems to be a little bit complicated to debug on github issues
If you want you can contact me on discord : lefuturiste#5297 or https://discord.gg/XwmtNuUG2w

I will also make a report here for others people.

**Comment by sardanian** [comment]
My BMI160 was faulty. Thank you for the follow up.

**Comment by lefuturiste** [comment]
no problem
